<template>
  <div id="app" class=".slide-in-bottom">
    <div id="container">
      <img id="avatar" alt="avatar" src="./assets/logo.png" />

      <h1>Jay Yan</h1>
      <h2>
        Web developer.
        <br />Porsche fan. 🚗
        <br />Batman fan. 🦇
      </h2>
      <span>
        * also the creator of
        <a
          href="https://chrome.google.com/webstore/detail/即刻喵-2/olbcannpdmfilamkfbmefmaagafhnlhb?hl=zh-CN"
        >'即刻喵'</a>
      </span>

      <div id="card-container">
        <Card
          msg="GitHub"
          backgroundColor="#24292E"
          textColor="#FFFFFF"
          icon="github.png"
          link="https://github.com/coder-ysj"
        />
      </div>

      <div id="others">
        <hr />
        <h3>You can also find me on:</h3>
        <div class="social-media">
          <div class="social-media-card">
            <img class="media-icon" src="@/assets/jike.png" alt />
            <span>
              即刻:
              <a
                href="https://web.okjike.com/user/4DDA0425-FB41-4188-89E4-952CA15E3C5E/post"
              >@盐酥鸡</a>
            </span>
          </div>

          <div class="social-media-card">
            <img class="media-icon" src="@/assets/twitter.png" alt />
            <span>
              Twitter:
              <a href="https://twitter.com/coder_ysj">@coder_ysj</a>
            </span>
          </div>
        </div>

        <hr />
        <p>Thank you for following me.</p>
      </div>
    </div>

    <div id="footer">
      <div id="footer-text">©{{ currentYear }} Jay Yan</div>
    </div>
  </div>
</template>

<script>
import Card from '@/components/Card'

export default {
  name: 'app',
  components: { Card },
  data() {
    return {
      currentYear: new Date().getFullYear()
    }
  }
}
</script>

<style>
body {
  margin: 0;
}

h1 {
  font-weight: 700;
  font-size: 28px;
}

h2 {
  font-weight: 400;
  font-size: 20px;
  padding: 20px 0;
}

hr {
  width: 100px;
  margin: 60px 0;
  border-top: solid 3px #141313;
}

span {
  color: #666666;
}

a {
  text-decoration: none;
  color: #c03237;
}

a:hover {
  border-bottom: #c03237 solid 1px;
}

div#app {
  font-family: 'Fira Mono', sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: #141313;
  -webkit-animation: slide-in-bottom 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    both;
  animation: slide-in-bottom 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

div#container {
  text-align: center;
  margin: 40px auto 0 auto;
  max-width: 600px;
  padding: 60px 20px;
}

img#avatar {
  width: 120px;
  height: 120px;
  border-radius: 60px;
}

div.social-media-card {
  display: flex;
  align-items: center;
  margin: 20px 0;
}

div.social-media-card img.media-icon {
  width: 30px;
  height: 30px;
  padding-right: 20px;
}

div#others {
  text-align: left;
}

div#footer {
  padding: 20px 20px;
  background-color: #141313;
  color: #ffffff;
}

div#footer-text {
  margin: 0px auto;
  max-width: 600px;
}

/* ----------------------------------------------
 * Generated by Animista on 2019-7-28 20:57:15
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-bottom
 * ----------------------------------------
 */
@keyframes slide-in-bottom {
  0% {
    -webkit-transform: translateY(1000px);
    transform: translateY(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
</style>
